[WIP] Shellcheck cleanup

diff --git a/tools/get_domains_by_account b/tools/get_domains_by_account
--- a/tools/get_domains_by_account
+++ b/tools/get_domains_by_account
@@ -27,13 +27,10 @@
 # Purpose of file: gives domains and sub-domains attached to an account
 # ----------------------------------------------------------------------
 #
-PATH=""
 PROG_NAME=get_domains_by_account
-PROG_VERSION=0.1.0
 ALTERNC_ETC=/etc/alternc
 ALTERNC_CONF_FILE=$ALTERNC_ETC/local.sh
 export TEXTDOMAIN=alternc-admintools
-
 
 # Be sure to use the right programs on Debian
 # and be sure they are there
@@ -54,31 +51,34 @@ done
 # Uses gettext and mo files.
 # Don't change these messages, change the .po file instead.
 HELP=$($gettext "Gives domains and sub-domains attached to an account.")
-USAGE=`$printf "$($gettext "Usage: %s account.")" $PROG_NAME`
-NOT_FOUND_MSG=$($gettext "does not exist.")
+USAGE=$($printf "$($gettext "Usage: %s account.")" $PROG_NAME)
 NON_ROOT_MSG=$($gettext "You have to be root (uid 0) to execute this program.")
-MISSING_PROG=$($gettext "Unable to execute")
-MISSING_CONF_FILE=`$printf "$($gettext "Can't find %s. Are you sure AlterncC is properly installed?")" $ALTERNC_CONF_FILE`
-MYSQL_UNREACHABLE_DATABASE=`$printf "$($gettext "Cannot access accounts database. Please check either %s or Mysql state.")" $ALTERNC_CONF_FILE`
+MISSING_CONF_FILE=$($printf "$($gettext "Can't find %s. Are you sure AlterncC is properly installed?")" $ALTERNC_CONF_FILE)
+MYSQL_UNREACHABLE_DATABASE=$($printf "$($gettext "Cannot access accounts database. Please check either %s or Mysql state.")" $ALTERNC_CONF_FILE)
 
 
 #-------------------------
 # Main
 #-------------------------
 # Must be root
-[ "`$id -u`" != "0" ] && { echo $NON_ROOT_MSG ; exit 1 ; }
+[ "$($id -u)" != "0" ] && { echo "$NON_ROOT_MSG" ; exit 1 ; }
 # Must have minimum 1 parameter
-[ -z "$1" ] && { echo $USAGE ; exit 1 ; }
+[ -z "$1" ] && { echo "$USAGE" ; exit 1 ; }
 # Handle -h and --help flags
-[ "$1" = "-h" ] || [ "$1" = "--help" ] && { echo $HELP ; echo $USAGE ; exit 0 ; }
+[ "$1" = "-h" ] || [ "$1" = "--help" ] && { echo "$HELP" ; echo "$USAGE" ; exit 0 ; }
 # Have to get AlternC conf file :
-! [ -f "$ALTERNC_CONF_FILE" ] && { echo $MISSING_CONF_FILE ; exit 1 ; } || . $ALTERNC_CONF_FILE
+if ! [ -f "$ALTERNC_CONF_FILE" ] ; then
+    echo "$MISSING_CONF_FILE"
+    exit 1
+fi
+# shellcheck disable=SC1090
+. "$ALTERNC_CONF_FILE"
 # Must have access to mysql to retreive accounts owning domains :
 mysql="$mysql --defaults-file=/etc/alternc/my.cnf -B -N -e"
-$mysql "desc domaines;" > /dev/null 2>&1
-[ "$?" != 0 ] && { echo "$MYSQL_UNREACHABLE_DATABASE" ; exit 1 ; }
+if ! $mysql "desc domaines;" > /dev/null 2>&1 ; then
+    echo "$MYSQL_UNREACHABLE_DATABASE"
+    exit 1
+fi
 
 # Does the stuff
 $mysql "select concat(a.sub, if(a.sub=\"\",\"\", \".\"), a.domaine) from sub_domaines a, membres b where a.compte = b.uid and b.login = \"${1}\";"
-
-
